### ISSUE TITLE
Time Tracker Not Loading

### ISSUE THREAD

**Issue by msugjw** [Strategery-Inc/jira-harvest-time-tracker#101]
We are using Cloud JIRA and the plugin doesn't seem to load for the past 2 days.  For the new 'view' on service desk issue it just doesn't show anything, on the old JIRA view it says App is not responding.
![jir_Harvest](https://user-images.githubusercontent.com/62754466/77762470-f5ddde00-700f-11ea-8282-9b3dad795dd2.png)

**Comment by gsomoza** [comment]
Hi @msugjw , we released a new version that should fix that issue just around the time you posted this. Could you please check again?

**Comment by msugjw** [comment]
I tested again with multiple browsers, clearing cache, signing out of Jira and still experiencing same issue.

**Comment by gsomoza** [comment]
@msugjw  could you check that you're running the latest version of the add-on? It's called [Harvester Real-Time Tracker](https://marketplace.atlassian.com/apps/1219223/harvester-real-time-tracking?hosting=cloud&tab=overview)

If you're running an old version then I recommend you to upgrade. 

If you're running the old add-on on a Cloud instance (called "Harvest Real-Time Tracking by Strategery") please get in touch via email for a pro-rated discount when you migrate to the new one: support (at) strategery (dot) io

**Comment by msugjw** [comment]
We are using 20180516.0.2-AC

Guessing that is the older version since I see your latest update on the marketplace is 3/27.   I'll contact support regarding pricing.
