### ISSUE TITLE
Login Loop JIRA Cloud

### ISSUE THREAD

**Issue by msugjw** [Strategery-Inc/jira-harvest-time-tracker#109]
**Describe the bug**
When trying to login to Harvest from JIRA it never fully authenticates and just loops back to Sign in.

**To Reproduce**
1. Click on the 'Sign into Harvest' button from any project\ticket in JIRA
2. On the 'Allow Access' screen that comes up click 'Approve'
3. It brings you back to the 'Sign into Harvest' button in JIRA ticket

**Expected behavior**
Would expect it to show Harvest plugin data

**Screenshots**
![image](https://user-images.githubusercontent.com/62754466/154514075-2949b66e-c777-4062-8847-f6ff24538d45.png)
![image](https://user-images.githubusercontent.com/62754466/154514105-bd75aa39-27e3-46f2-b0db-f7b84b77c069.png)
![image](https://user-images.githubusercontent.com/62754466/154514124-9eb7e0f8-9387-4bde-81b4-5c245aedfdb3.png)

**Browser Console Logs**
Attached
[console-export-2022-2-17_10-31-3.txt](https://github.com/Strategery-Inc/jira-harvest-time-tracker/files/8089929/console-export-2022-2-17_10-31-3.txt)

**Please complete the following information:**
 - JIRA Type: Cloud
 - Browser Type: Chrome and Firefox
 - Browser Version: Chrome 98.0.4758.82 and Firefox 97.0

**Comment by DobyTang** [comment]
Confirmed
Chrome - Version 98.0.4758.80 (Official Build) (x86_64)
OS : OSX 12.2

**Comment by HOMEdigital** [comment]
Same with Jira Server v8.20.5
after updating this plugin in Jira i only get "invalid_request" in the window of the 2. step where i had to click "Approve"

Chrome - Version 98.0.4758.82 (Offizieller Build) (64-Bit)
Firefox - 97.0
Windows 11 - Version 10.0.22000 Build 22000

**Comment by TonyCiniglioMT** [comment]
Same here - none of my team can connect between Harvest and Jira.
Across a range of OS and browser types.
Used to work perfectly.

**Comment by HOMEdigital** [comment]
This solved the problem for us: https://github.com/Strategery-Inc/jira-harvest-time-tracker/issues/108#issuecomment-994937840

**Comment by gsomoza** [comment]
We found the issue and it should be fixed as of yesterday on all Jira Cloud installs. We don't expect the issue to happen again because it was related to a change in the Harvest API. If anyone still has issues logging in please let me know!

**Comment by gsomoza** [comment]
For users running Jira Server please see indeed #108 for the resolution.

**Comment by msugjw** [comment]
We are still experiencing the same issue on JIRA cloud, I checked to see if there was an update to the app but it does not show one in my JIRA admin.  We are using version 20180516.0.7-AC

**Comment by ksartain** [comment]
Confirmed that we are still running into this issue on Jira Cloud. Please let us know when to expect an update. Thanks!

**Comment by gsomoza** [comment]
@msugjw judging by the version number you cited (which is from 2018) it's possible that you're running on an archived App. @ksartain that may be your situation too.

Our development team for this tool is in Ukraine (Kiev) and hardly operational at this moment, which is why we're having issues to provide technical support. I'm still in touch with our developer there so I'll add a fix for the archived plugin to his queue, but I can't provide an ETA at the moment.

So what I would recommend in your case is to upgrade to the App that's actively being developed and maintained –  which is also the one that was patched 14 days ago: [Harvester Real-Time Tracking](https://marketplace.atlassian.com/apps/1219223/harvester-real-time-tracking?tab=overview&hosting=cloud)

**Comment by gsomoza** [comment]
Documentation page for troubleshooting: https://github.com/Strategery-Inc/jira-harvest-time-tracker/wiki/Debugging-Issues-with-Login
